# QEMU hardware is fully predictable so this file is authored directly rather
# than generated by nixos-generate-config.
#
# fileSystems is intentionally absent — disko generates it from disk-config.nix.
{ modulesPath, lib, ... }: {
  imports = [
    # NixOS QEMU guest profile: enables virtio balloon driver, guest agent
    # optimisations, and marks the system as a VM for NixOS internals.
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
}
